import type { Metadata } from "next";
<<<<<<< HEAD
import "../styles/globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
=======
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Provider from "../providers/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
>>>>>>> main

export const metadata: Metadata = {
  title: "Reviewer Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body>
        {" "}
        <ReduxProvider>{children}</ReduxProvider>{" "}
=======
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>{children}</Provider>
>>>>>>> main
      </body>
    </html>
  );
}
