import type { Metadata } from "next";
import "../styles/globals.css";
import Provider from "../providers/ReduxProvider";
import { ApplicationFormProviderEdit } from "@/hooks/ApplicationFormContext";
import { ApplicationFormProvider } from "@/lib/context/ApplicationFormContext";

export const metadata: Metadata = {
  title: "Application platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          {" "}
          <ApplicationFormProviderEdit>
            <ApplicationFormProvider>{children} </ApplicationFormProvider>
          </ApplicationFormProviderEdit>
        </Provider>
      </body>
    </html>
  );
}
