import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
<<<<<<< HEAD
import "./styles/globals.css";
import Provider from "./providers/ReduxProvider";
=======
import "./globals.css";
>>>>>>> my-local-backup

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Reviewer Dashboard",
=======
  title: "Create Next App",
>>>>>>> my-local-backup
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <Provider>{children}</Provider>
=======
        {children}
>>>>>>> my-local-backup
      </body>
    </html>
  );
}
